<<<<<<< HEAD
# Generated by Django 2.1 on 2019-02-19 14:19

import datetime
=======
# Generated by Django 2.1.5 on 2019-02-27 14:22

from django.conf import settings
>>>>>>> d057f28c8115c1d76ca936d9ab70d4b9837a7541
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
=======
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
>>>>>>> d057f28c8115c1d76ca936d9ab70d4b9837a7541
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='Apply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=datetime.datetime(2019, 2, 19, 14, 19, 42, 700455))),
                ('date_modified', models.DateTimeField(blank=True, default=datetime.datetime(2019, 2, 19, 14, 19, 42, 700487), null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/images')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=datetime.datetime(2019, 2, 19, 14, 19, 42, 699789))),
                ('date_modified', models.DateTimeField(blank=True, default=datetime.datetime(2019, 2, 19, 14, 19, 42, 699827), null=True)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='job_platform.Job')),
            ],
        ),
        migrations.AddField(
            model_name='apply',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='job_platform.Job'),
=======
            name='JobPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('description', models.TextField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp', '-updated'],
            },
>>>>>>> d057f28c8115c1d76ca936d9ab70d4b9837a7541
        ),
    ]
