# Generated by Django 2.1 on 2019-02-24 10:39

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job_platform', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='apply',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 24, 10, 39, 36, 364473)),
        ),
        migrations.AlterField(
            model_name='apply',
            name='date_modified',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 2, 24, 10, 39, 36, 364506), null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 24, 10, 39, 36, 363809)),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_modified',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 2, 24, 10, 39, 36, 363849), null=True),
        ),
    ]
