# Generated by Django 2.1 on 2019-02-24 10:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_platform', '0002_auto_20190224_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 24, 10, 57, 10, 2386)),
        ),
        migrations.AlterField(
            model_name='apply',
            name='date_modified',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 2, 24, 10, 57, 10, 2421), null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 24, 10, 57, 10, 1768)),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_modified',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 2, 24, 10, 57, 10, 1807), null=True),
        ),
    ]
