# Generated by Django 2.1.5 on 2019-03-01 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_platform', '0002_auto_20190301_0554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
