# Generated by Django 2.1 on 2019-02-24 11:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_platform', '0003_auto_20190224_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 24, 11, 9, 36, 38051)),
        ),
        migrations.AlterField(
            model_name='apply',
            name='date_modified',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 2, 24, 11, 9, 36, 38087), null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 24, 11, 9, 36, 37412)),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_modified',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 2, 24, 11, 9, 36, 37450), null=True),
        ),
    ]
