# Generated by Django 2.1.5 on 2019-03-01 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_platform', '0004_auto_20190301_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='image',
            field=models.ImageField(blank=True, default='images/default_thumbnail.png', null=True, upload_to='images/'),
        ),
    ]
