# Generated by Django 2.1.5 on 2019-03-02 12:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job_platform', '0005_auto_20190301_0944'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('documents', models.FileField(blank=True, null=True, upload_to='docs/')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('date_applied', models.DateTimeField(auto_now_add=True)),
                ('archived', models.BooleanField(default=True)),
                ('applicant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_applied', '-updated'],
            },
        ),
        migrations.AddField(
            model_name='jobpost',
            name='archived',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='application',
            name='jobpost',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='post', to='job_platform.JobPost'),
        ),
    ]
