# Generated by Django 2.1.5 on 2019-03-02 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job_platform', '0006_auto_20190302_1210'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('displaypic', models.ImageField(blank=True, default='profilepics/default_pic.png', null=True, upload_to='profilepics/')),
                ('company', models.CharField(blank=True, max_length=100)),
                ('about', models.TextField(blank=True, max_length=500)),
                ('location', models.CharField(blank=True, max_length=30)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('resume', models.FileField(blank=True, null=True, upload_to='resume/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='application',
            name='documents',
        ),
        migrations.AlterField(
            model_name='application',
            name='applicant',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='job_platform.Profile'),
        ),
        migrations.AlterField(
            model_name='application',
            name='archived',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='archived',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='author',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='recruiter', to='job_platform.Profile'),
        ),
    ]
