# Generated by Django 2.1.5 on 2019-03-03 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_platform', '0009_auto_20190302_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='author',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='recruiter', to='job_platform.Profile'),
        ),
    ]
