# Generated by Django 2.1.5 on 2019-03-03 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_platform', '0012_auto_20190303_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='jobpost',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to='job_platform.JobPost'),
        ),
    ]
