# Generated by Django 2.1.5 on 2019-03-03 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_platform', '0014_auto_20190303_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='jobpost',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post', to='job_platform.JobPost'),
        ),
    ]
