# Generated by Django 2.1.5 on 2019-03-03 11:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_platform', '0015_auto_20190303_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='applicant',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='recruits', to=settings.AUTH_USER_MODEL),
        ),
    ]
