# Generated by Django 2.1.5 on 2019-03-03 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_platform', '0016_auto_20190303_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='company',
            field=models.CharField(default='N/A', max_length=100),
        ),
    ]
