# Generated by Django 2.1.5 on 2019-03-04 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_platform', '0017_auto_20190303_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
