# Generated by Django 2.1.5 on 2019-03-04 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_platform', '0019_auto_20190304_0700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
